# Generated by Django 4.2.4 on 2023-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_is_paid_orderitem_discounted_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('35', '4'), ('36', '5'), ('37', '6'), ('38', '7'), ('39', '8'), ('40', '9'), ('41', '10'), ('42', '11'), ('43', '12'), ('44', '13')], default='36', max_length=10),
        ),
    ]
