# Generated by Django 4.2.4 on 2023-11-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('4', '35'), ('5', '36'), ('6', '37'), ('7', '38'), ('8', '39'), ('9', '40'), ('10', '41'), ('11', '42'), ('12', '43'), ('13', '44')], default='36', max_length=10),
        ),
    ]
